image: "rust:latest"

stages:
  - build
  - format

build:
  stage: build
  image: rust:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - .cargo/
  script:
    - rustup target add thumbv7em-none-eabi thumbv7em-none-eabihf
    - cargo build

format:
  stage: format
  cache:
    key: "$CI_COMMIT_REF_SLUG-format"
    paths:
      - target/
      - .cargo/
  script:
    - rustup target add thumbv7em-none-eabi thumbv7em-none-eabihf
    - cargo fmt --all
    - git add .
    - git diff-index --quiet HEAD || git commit -m "[ci] formatting with cargo fmt"
  only:
    - main
