image: "rust:latest"

stages:
  - build

build:
  stage: build
  image: rust:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - target/
      - .cargo/
  script:
    - rustup target add thumbv7em-none-eabi thumbv7em-none-eabihf
    - cargo build
