[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32L433RCTx"
rustflags = [
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
# Cortex-M4 or Cortex-M7 (with FPU)
target = "thumbv7em-none-eabihf"
